echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo " I am learning Devops"
echo "my carreer has been started now"
echo "HELLO DOSTO"
echo "let's start with git"
echo "hello buddy this is for test"

